import json,re
from pathlib import Path
root=Path.cwd()
files=[Path(p) for p in json.loads(Path('graphify-out/.files_05.json').read_text())][:9]
texts=[p.read_text(encoding='utf-8-sig') for p in files]
nodes={};edges=[];hyperedges=[]
def cid(label):return 'dayz_'+re.sub('[^a-z0-9]+','_',label.lower()).strip('_')
def location(i,label):
    return 'L'+str(next((j+1 for j,s in enumerate(texts[i].splitlines()) if label.lower() in s.lower()),1))
def node(label,i,rationale=None):
    nid=cid(label)
    if nid not in nodes:nodes[nid]=dict(id=nid,label=label,file_type='rationale',source_file=files[i].relative_to(root).as_posix(),source_location=location(i,label),source_url=None,captured_at=None,author=None,contributor=None)
    if rationale:nodes[nid]['rationale']=rationale
    return nid
def edge(a,b,i,description,rel='references'):
    edges.append(dict(source=a,target=b,relation=rel,description=description,confidence='EXTRACTED',confidence_score=1.0,source_file=files[i].relative_to(root).as_posix(),source_location=location(i,nodes[a]['label']) if a.startswith('dayz_') else location(i,nodes[b]['label']),weight=1.0))
def pair(a,b,i,description,rel='references'):edge(node(a,i),node(b,i),i,description,rel)
concepts=[
['Mod scaffold','mod.cpp','config.cpp','CfgPatches','CfgMods','Script layers','Addon Builder','DayZDiag','File patching','Workbench','Professional mod template'],
['Script logs','Print','DayZDiag','File patching','Workbench','Dedicated server testing','Listen server','Class.CastTo','Script layers','Debug logging'],
['Steam Workshop','SteamCMD','Publisher','PBO','DSCreateKey','DSSignFile','bikey','biprivatekey','bisign','mod.cpp','Semantic versioning','Config migration'],
['ServerInfoHUD','ScriptedWidgetEventHandler','MissionGameplay','PlayerBase','ScriptRPC','UAInput','inputs.xml','WidgetFadeTimer','Timer accumulator','Widget.Unlink','UIManager','CfgMods'],
['Professional mod template','MyModManager','MyModConfig','MyModRPCHelper','MyModUI','DayZGame','ScriptRPC','MissionServer','MissionGameplay','JsonFileLoader','stringtable.csv','inputs.xml'],
['MFM_RallyHatchback','OffroadHatchback','CarScript','SimulationModule','DamageSystem','Hidden selections','events.xml','cfgspawnabletypes.xml','cfgeventspawns.xml','OnDebugSpawn','TexView2','CfgSoundSets'],
['MCM_TacticalJacket_ColorBase','MCM_TacticalJacket_Woodland','GorkaEJacket_ColorBase','Top_Base','Clothing_Base','heatIsolation','Hidden selections','DamageSystem','types.xml','stringtable.csv','OnWasAttached','OnWasDetached'],
['ShopDemoManager','ShopDemoMenu','ShopConfig','ShopCategory','ShopItem','ShopDemoRPC','JsonFileLoader','GameInventory','Server-side validation','DeleteSafe','CreateInInventory','CreateObjectEx'],
['Diag Menu','DayZDiag','EnProfiler','Script profiler','FreeDebugCamera','Bullet physics','Geometry diagnostic','CEApi','Central Economy','NavMesh','Sound diagnostics','Post-process effects']]
for i,p in enumerate(files):
    title=next(s[2:] for s in texts[i].splitlines() if s.startswith('# '))
    did='doc_'+re.sub('[^a-z0-9]+','_',p.relative_to(root).as_posix().lower()).strip('_')
    nodes[did]=dict(id=did,label=title,file_type='document',source_file=p.relative_to(root).as_posix(),source_location='L1',source_url=None,captured_at=None,author=None,contributor=None)
    for label in concepts[i]:edge(did,node(label,i),i,'Documents '+label)

for a,b,d in [('Mod scaffold','config.cpp','Scaffold provides script registration configuration'),('Mod scaffold','mod.cpp','Scaffold provides launcher metadata'),('config.cpp','CfgMods','Registers script module paths'),('config.cpp','CfgPatches','Declares patch and required addons'),('CfgMods','Script layers','Maps scripts into 3_Game, 4_World and 5_Mission'),('Addon Builder','PBO','Packs the scaffold for testing'),('DayZDiag','File patching','Development executable loads loose files during iteration'),('Mod scaffold','Professional mod template','Chapter links the professional template for configuration, RPC and UI scaffolding')]:pair(a,b,0,d)
node('Mod scaffold',0,'Correct layer registration and consistent mod paths prevent silent script loading failures.')
for a,b,d in [('Print','Script logs','Debug prints appear in script logs'),('Debug logging','Print','Uses tagged prints to isolate mod messages'),('DayZDiag','File patching','Supports development with unpacked files'),('Workbench','Script layers','Provides script syntax and development environment'),('Dedicated server testing','ScriptRPC','Tests client/server RPC boundaries'),('Listen server','Dedicated server testing','Listen-server testing may hide networking problems found with a separate server'),('Class.CastTo','PlayerBase','Safely casts the local player with failure checks')]:pair(a,b,1,d)
node('Dedicated server testing',1,'Separate server and client processes reveal RPC authority, timing and missing-identity issues that a listen server can hide.')
for a,b,d in [('DSCreateKey','bikey','Generates public verification key'),('DSCreateKey','biprivatekey','Generates private signing key'),('DSSignFile','biprivatekey','Uses private key to sign packed addons'),('DSSignFile','PBO','Signs each addon archive'),('DSSignFile','bisign','Produces addon signature files'),('bisign','bikey','Server verifies signatures against the public key'),('Publisher','Steam Workshop','Uploads and updates Workshop entries'),('SteamCMD','Steam Workshop','Publishes through workshop_build_item and a VDF'),('Steam Workshop','mod.cpp','Release package contains launcher metadata'),('Semantic versioning','Config migration','Breaking saved-data changes require migration and major-version consideration')]:pair(a,b,2,d)
node('biprivatekey',2,'Keep the private signing key out of the public release and retain the same key for compatible updates.')
for a,b,d in [('ServerInfoHUD','ScriptedWidgetEventHandler','Extends widget event handler'),('MissionGameplay','ServerInfoHUD','Creates, updates and destroys the HUD'),('ServerInfoHUD','ScriptRPC','Requests server information using serialized RPC'),('PlayerBase','ScriptRPC','Handles server request and client response RPC'),('ServerInfoHUD','Timer accumulator','Throttles periodic updates to one second'),('MissionGameplay','UAInput','Checks the HUD toggle action'),('CfgMods','inputs.xml','Registers the input definition file'),('ServerInfoHUD','WidgetFadeTimer','Optional fade animation controls overlay visibility'),('MissionGameplay','UIManager','Checks menus before showing overlay'),('ServerInfoHUD','Widget.Unlink','Destroys widget tree when the HUD is torn down')]:pair(a,b,3,d)
node('Timer accumulator',3,'Periodic HUD refresh avoids sending server-info requests on every frame.')
for a,b,d in [('MyModManager','MyModConfig','Owns and loads server configuration'),('MyModConfig','JsonFileLoader','Loads and saves profile JSON configuration'),('MyModManager','MyModRPCHelper','Sends client responses through RPC helper'),('MyModRPCHelper','ScriptRPC','Serializes route name followed by payload'),('DayZGame','ScriptRPC','Dispatches the shared RPC identifier and reads its string route'),('DayZGame','MyModManager','Forwards server UI requests to manager'),('DayZGame','MissionGameplay','Forwards client RPC messages to mission'),('MissionServer','MyModManager','Initializes, updates and shuts down manager'),('MissionGameplay','MyModUI','Creates and toggles client UI'),('MyModUI','Widget.Unlink','Destructor releases its root widget'),('Professional mod template','stringtable.csv','Includes localized interface text'),('Professional mod template','inputs.xml','Includes rebindable toggle input')]:pair(a,b,4,d)
node('MyModManager',4,'A singleton centralizes mission state; initialization guards and shutdown cleanup prevent duplicate active managers.')
node('MyModConfig',4,'Public defaults remain useful when older configuration files omit newly introduced fields.')
for a,b,d in [('MFM_RallyHatchback','OffroadHatchback','Extends vanilla hatchback configuration and script class'),('OffroadHatchback','CarScript','Vanilla vehicle uses the CarScript hierarchy'),('MFM_RallyHatchback','SimulationModule','Configures torque, gearing and driving properties'),('MFM_RallyHatchback','DamageSystem','Configures vehicle damage zones'),('MFM_RallyHatchback','Hidden selections','Assigns custom body textures'),('TexView2','Hidden selections','Converts custom texture to PAA for hiddenSelectionsTextures'),('events.xml','MFM_RallyHatchback','Registers vehicle as event child class'),('cfgeventspawns.xml','events.xml','Supplies coordinates to the matching vehicle event'),('cfgspawnabletypes.xml','MFM_RallyHatchback','Defines attached parts and spawn probabilities'),('OnDebugSpawn','MFM_RallyHatchback','Equips parts and fills fluids for debug spawning'),('MFM_RallyHatchback','CfgSoundSets','References custom horn sound sets')]:pair(a,b,5,d)
node('MFM_RallyHatchback',5,'Extending a vanilla vehicle preserves its model rig, animations and underlying simulation while customizing behavior and appearance.')
for a,b,d in [('MCM_TacticalJacket_ColorBase','GorkaEJacket_ColorBase','Extends vanilla jacket base'),('GorkaEJacket_ColorBase','Top_Base','Uses vanilla upper-body clothing hierarchy'),('Top_Base','Clothing_Base','Belongs to clothing inheritance chain'),('MCM_TacticalJacket_Woodland','MCM_TacticalJacket_ColorBase','Concrete texture variant inherits common properties'),('MCM_TacticalJacket_ColorBase','heatIsolation','Sets insulation property'),('MCM_TacticalJacket_ColorBase','DamageSystem','Configures protection and material health levels'),('MCM_TacticalJacket_Woodland','Hidden selections','Assigns ground and worn textures'),('types.xml','MCM_TacticalJacket_Woodland','Registers the concrete clothing variant in central economy'),('MCM_TacticalJacket_ColorBase','stringtable.csv','References localized display name and description'),('OnWasAttached','PlayerBase','Optional script applies equip effects to wearer'),('OnWasDetached','PlayerBase','Optional script removes equip effects')]:pair(a,b,6,d)
node('MCM_TacticalJacket_ColorBase',6,'A hidden common base shares clothing properties while public concrete variants select textures.')
node('heatIsolation',6,'Actual warmth also depends on clothing condition and wetness, beyond the base insulation value.')
for a,b,d in [('ShopConfig','ShopCategory','Contains shop categories'),('ShopCategory','ShopItem','Contains items with class names and buy/sell prices'),('ShopDemoManager','ShopConfig','Owns authoritative shop configuration'),('ShopDemoManager','JsonFileLoader','Loads or writes profile shop configuration'),('ShopDemoManager','GameInventory','Enumerates player currency and owned sale items'),('ShopDemoManager','DeleteSafe','Deletes currency or sold items before granting the return'),('ShopDemoManager','CreateInInventory','Creates purchased items and currency in inventory'),('ShopDemoManager','CreateObjectEx','Falls back to ground creation when inventory is full'),('ShopDemoManager','Server-side validation','Validates quantity, catalog item, currency and ownership'),('ShopDemoMenu','ShopDemoRPC','Requests catalog and submits buy/sell actions'),('PlayerBase','ShopDemoRPC','Dispatches server shop requests'),('DayZGame','ShopDemoMenu','Forwards response data through the client mission to menu')]:pair(a,b,7,d)
node('Server-side validation',7,'The client supplies item class and quantity; server catalog prices and inventory determine whether a trade can proceed.')
node('ShopDemoRPC',7,'The tutorial delimiter format is fragile when labels contain delimiters; structured serialization is recommended for production.')
node('ShopItem',7,'Keeping the sell price below the buy price prevents a profitable buy-sell loop.')
for a,b,d in [('DayZDiag','Diag Menu','Diagnostic executable exposes the diagnostic menu'),('Diag Menu','Script profiler','Provides script profiling controls'),('Script profiler','EnProfiler','Script API configures profiler recording and modules'),('Diag Menu','FreeDebugCamera','Provides free-camera debug inspection'),('Diag Menu','Bullet physics','Visualizes collision shapes, contacts and centers of mass'),('Diag Menu','Geometry diagnostic','Visualizes view, fire and memory geometry'),('Diag Menu','CEApi','Many central economy menu actions have script API equivalents'),('CEApi','Central Economy','Exposes loot spawn editing and economy diagnostics'),('CEApi','FreeDebugCamera','Loot volume editing requires free camera'),('Diag Menu','NavMesh','AI diagnostics visualize navigation and path agents'),('Diag Menu','Sound diagnostics','Shows active samples and sound system statistics'),('Diag Menu','Post-process effects','Controls rendering effect diagnostics')]:pair(a,b,8,d)
node('Script profiler',8,'Profiling adds overhead; disable it for baseline FPS measurements. Native proto work is attributed to the calling script function.')
node('CEApi',8,'Most CE debug tools require single-player with CE enabled; the chapter identifies Building Stats as the multiplayer exception.')
hyperedges.append(dict(id='chunk05_signing_chain',label='Signed addon verification',nodes=[cid(x) for x in ['PBO','bisign','bikey','biprivatekey']],relation='participate_in',confidence='EXTRACTED',confidence_score=1.0,source_file=files[2].relative_to(root).as_posix(),source_location=location(2,'DSSignFile')))
result=dict(nodes=list(nodes.values()),edges=edges,hyperedges=hyperedges,input_tokens=0,output_tokens=0)
assert all(e['source'] in nodes and e['target'] in nodes for e in edges)
Path('graphify-out/.graphify_chunk_05_tutorial.json').write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf-8')
print(len(nodes),len(edges),len(hyperedges))
