import json,re
from pathlib import Path
files=[Path(f).resolve().relative_to(Path.cwd()).as_posix() for f in json.loads(Path('graphify-out/.files_04.json').read_text(encoding='utf-8-sig'))]
nodes={};edges=[];texts={f:Path(f).read_text(encoding='utf-8-sig') for f in files}
def cid(s):return 'dayz_'+re.sub('[^a-z0-9]+','_',s.lower()).strip('_')
def loc(f,word):
    lines=texts[f].splitlines()
    for i,line in enumerate(lines):
        if word.lower() in line.lower():return 'line '+str(i+1)
    return 'line 1'
def node(label,f,why=None):
    k=cid(label)
    if k not in nodes:nodes[k]=dict(id=k,label=label,file_type='rationale',source_file=f,source_location=loc(f,label),source_url=None,captured_at=None,author=None,contributor=None)
    if why:nodes[k]['rationale']=why
    return k
def edge(a,b,f,relation='references',why=None,confidence='EXTRACTED',score=1.0):
    d=dict(source=a,target=b,relation=relation,confidence=confidence,confidence_score=score,source_file=f,source_location=loc(f,why or nodes.get(a,{}).get('label','')),weight=1.0)
    if why:d['description']=why
    edges.append(d)
specs=[
('SEffectManager|EffectSound|CfgSoundShaders|CfgSoundSets|SoundParams|SoundObjectBuilder|SoundObject|AbstractSoundScene|AbstractWave|WaveKind|ScriptInvoker',[
('SEffectManager','EffectSound','references','Creates and registers sound effects'),('EffectSound','SoundParams','references','Validates named soundset configuration'),('SoundObjectBuilder','SoundParams','references','Constructor receives SoundParams'),('SoundObjectBuilder','SoundObject','calls','BuildSoundObject creates playable definition'),('AbstractSoundScene','AbstractWave','references','Play3D returns live sound handle'),('EffectSound','AbstractWave','references','Wraps low-level wave playback'),('CfgSoundSets','CfgSoundShaders','references','soundShaders array links sample configurations'),('EffectSound','WaveKind','references','Selects audio channel with SetSoundWaveKind'),('EffectSound','ScriptInvoker','references','Exposes sound lifecycle callbacks')]),
('RecipeBase|PluginRecipesManagerBase|PluginRecipesManager|CraftingManager|CacheObject|ActionWorldCraft|CAContinuousCraft|TurnItemIntoItemLambda|ActionContinuousBase',[
('PluginRecipesManagerBase','RecipeBase','references','RegisterRecipies registers recipe subclasses'),('CraftingManager','PluginRecipesManager','calls','Queries GetValidRecipes'),('PluginRecipesManager','CacheObject','references','Caches ingredient class recipe membership'),('CraftingManager','ActionWorldCraft','references','Sets recipe action and variant'),('ActionWorldCraft','CAContinuousCraft','references','Uses recipe duration for progress'),('ActionWorldCraft','PluginRecipesManager','calls','OnFinishProgressServer performs recipe'),('PluginRecipesManager','RecipeBase','calls','Performs validation and result spawning'),('TurnItemIntoItemLambda','RecipeBase','conceptually_related_to','Document discusses inventory-preserving item transformations'),('ActionContinuousBase','RecipeBase','conceptually_related_to','Alternative action-based crafting for specialized transformations')]),
('BaseBuildingBase|Construction|ConstructionPart|Fence|Watchtower|ShelterSite|ActionBuildPart|ActionBuildShelter|CfgVehicles|OnVariablesSynchronized|DamageSystem',[
('BaseBuildingBase','Construction','references','Owns construction manager'),('Construction','ConstructionPart','references','Manages named construction parts'),('Fence','BaseBuildingBase','implements','Extends base building entity'),('Watchtower','BaseBuildingBase','implements','Extends base building entity'),('ShelterSite','BaseBuildingBase','implements','Buildable shelter foundation'),('Construction','CfgVehicles','references','Reads materials and part dependencies from Construction config'),('ActionBuildPart','Construction','calls','BuildPartServer consumes materials'),('ActionBuildShelter','ShelterSite','references','Transforms completed site into shelter'),('BaseBuildingBase','OnVariablesSynchronized','references','Reconstructs built parts from synchronization bitmasks'),('DamageSystem','Construction','references','Ruined damage zones trigger part destruction')]),
('HumanMovementState|HumanCommandMove|HumanCommandVehicle|HumanCommandScript|HumanAnimInterface|EmoteManager|EmoteBase|EmoteConstructor|HumanCommandActionCallback|SetAnimationPhase|model.cfg',[
('HumanCommandScript','HumanAnimInterface','references','Binds animation graph variables and commands'),('EmoteManager','EmoteConstructor','calls','ConstructEmotes builds registered emote list'),('EmoteConstructor','EmoteBase','references','Registers emote definitions'),('EmoteManager','HumanCommandActionCallback','references','EmoteCB is a command-action callback'),('SetAnimationPhase','model.cfg','references','Animation source name must match model configuration'),('HumanMovementState','HumanCommandMove','conceptually_related_to','Human command system exposes current movement state'),('HumanCommandVehicle','HumanCommandMove','conceptually_related_to','Only one main command is active at a time')]),
('CGame|SurfaceY|SurfaceRoadY|SurfaceDetectionParameters|SurfaceDetectionResult|CfgSurfaces|DayZPhysics|RaycastRVParams|RaycastRVResult|World|WorldData',[
('CGame','SurfaceY','references','Raw terrain height excludes roads and objects'),('CGame','SurfaceRoadY','references','Terrain height including road surfaces'),('SurfaceDetectionParameters','SurfaceDetectionResult','conceptually_related_to','GetSurface fills a structured result from parameters'),('CGame','CfgSurfaces','references','Surface queries report configured material names'),('DayZPhysics','RaycastRVParams','references','RaycastRVProxy uses structured query'),('DayZPhysics','RaycastRVResult','references','RaycastRVProxy fills hit results including proxies'),('WorldData','World','conceptually_related_to','Map-specific environment configuration complements world queries')]),
('ParticleList|ParticleBase|Particle|ParticleSource|ParticleManager|ParticleProperties|EffectParticle|SEffectManager|ParticleEffecter|EmitorParam|Particle Editor',[
('Particle','ParticleBase','implements','Legacy particle API derives from base'),('ParticleSource','ParticleBase','implements','Modern particle implementation derives from base'),('ParticleManager','ParticleSource','references','Owns pooled particle instances'),('ParticleManager','ParticleProperties','references','Configures source creation flags and ownership'),('ParticleList','Particle Editor','conceptually_related_to','Registers ptc definitions created in Workbench'),('EffectParticle','ParticleManager','calls','Creates managed particle during effect start'),('SEffectManager','EffectParticle','references','Registers and destroys high-level particle effects'),('ParticleEffecter','ParticleSource','conceptually_related_to','Synchronizes state for client-side particle rendering'),('ParticleSource','EmitorParam','references','Emitter parameters control runtime appearance')]),
('EntityAI|DayZCreatureAI|DayZInfected|ZombieBase|DayZInfectedInputController|DayZInfectedType|AITargetCallbacksPlayer|NoiseAIEvaluate|AIWorld|AIGroup|ECE_INITAI|InfectedSoundEventHandler',[
('DayZInfected','DayZCreatureAI','implements','Infected extends AI creature base'),('ZombieBase','DayZInfected','implements','Adds script command and combat logic'),('ZombieBase','DayZInfectedInputController','references','Reads AI mind state and target inputs'),('DayZInfectedType','ZombieBase','references','Selects registered attacks by utility conditions'),('AITargetCallbacksPlayer','ZombieBase','conceptually_related_to','Player visibility affects infected detection'),('NoiseAIEvaluate','ZombieBase','conceptually_related_to','Player noise contributes to detection'),('AIWorld','AIGroup','references','Creates groups and manages navigation'),('ECE_INITAI','DayZInfected','references','Required initialization flag for functional spawned infected'),('InfectedSoundEventHandler','ZombieBase','references','Client sound changes follow synchronized mind states')]),
('PlayerBase|PlayerIdentity|DisconnectPlayer|LNT_KickService|LNT_BanManager|JsonFileLoader|PluginAdminLog|LNT_Permissions|LNT_RPC|RestApi|Hive|World',[
('PlayerBase','PlayerIdentity','references','GetIdentity exposes account and connection identity'),('LNT_KickService','DisconnectPlayer','calls','Deferred disconnect after reason notification'),('LNT_KickService','LNT_RPC','calls','Sends reason before disconnect'),('LNT_BanManager','JsonFileLoader','calls','Persists ban records in profile directory'),('LNT_Permissions','PlayerIdentity','references','Checks authenticated sender GetPlainId'),('PluginAdminLog','PlayerBase','references','Logs server administrative player actions'),('RestApi','JsonFileLoader','conceptually_related_to','Chapter contrasts native HTTP webhook transport and JSON persistence'),('Hive','PlayerBase','references','CharacterSave CharacterKill CharacterExit persist player lifecycle')]),
('cfgEffectArea.json|EffectAreaLoader|ContaminatedArea_Static|ContaminatedTrigger|cfgundergroundtriggers.json|EyeAccommodation|cfgweather.xml|Weather|cfgGameplay.json|serverDZ.cfg|Object Spawner|Central Economy',[
('EffectAreaLoader','cfgEffectArea.json','references','Loads static effect area definitions'),('EffectAreaLoader','ContaminatedArea_Static','references','Creates configured area entities'),('ContaminatedArea_Static','ContaminatedTrigger','references','Associates gas effect area with player damage trigger'),('cfgundergroundtriggers.json','EyeAccommodation','references','Defines darkness triggers and weighted breadcrumbs'),('cfgweather.xml','Weather','references','Declarative phenomenon limits and forecast state'),('serverDZ.cfg','cfgGameplay.json','references','enableCfgGameplayFile activates gameplay configuration'),('cfgGameplay.json','Object Spawner','references','objectSpawnersArr lists placement files'),('Object Spawner','Central Economy','references','Runs after CE initialization; interaction can enable item persistence')]),
('EntityAI|GameInventory|PlayerIdentity|Weather|JsonFileLoader|ScriptCallQueue|Timer|ScriptInvoker|WorkspaceWidget|ScriptRPC|ParamsReadContext|ActionBase',[
('EntityAI','GameInventory','calls','GetInventory retrieves inventory component'),('WorkspaceWidget','CreateWidgets','references','Loads layout file into widget tree'),('ScriptRPC','ParamsReadContext','shares_data_with','Receiver deserializes the same field order and types'),('ScriptCallQueue','Timer','conceptually_related_to','Scheduling alternatives with milliseconds versus seconds'),('Weather','WeatherPhenomenon','references','Provides overcast rain fog snow and wind phenomena'),('ActionBase','ActionCondition','references','Validates custom action conditions')]),
('Singleton Pattern|GetInstance|DestroyInstance|MissionServer|MissionGameplay|LanternCore|LNT_ModuleManager|LNT_BanManager|PluginManager|PluginBase|PluginAdminLog|LNT_Log',[
('Singleton Pattern','GetInstance','references','Lazy accessor retains private static ref instance'),('Singleton Pattern','DestroyInstance','references','Explicit mission-end teardown releases static state'),('MissionServer','DestroyInstance','calls','OnMissionFinish sample tears down singleton'),('LanternCore','LNT_ModuleManager','calls','ShutdownAll centralizes subsystem cleanup'),('LanternCore','LNT_BanManager','conceptually_related_to','Singleton variants are illustrated by constructed Lantern subsystems'),('PluginManager','PluginBase','references','Owns one instance per registered plugin type'),('PluginAdminLog','PluginBase','implements','Vanilla singleton plugin example'),('LNT_Log','Singleton Pattern','conceptually_related_to','Static-only alternative when no instance is needed')]),
('PluginBase|PluginManager|MissionBase|JsonFileLoader|LNT_AutoConfigPlugin|LNT_ModuleBase|LNT_ServerModule|LNT_ClientModule|LNT_ModuleManager|LNT_RPC|Community Framework',[
('MissionBase','PluginManager','references','Constructor initializes plugin manager'),('PluginManager','PluginBase','references','RegisterPlugin side flags govern instantiation and update'),('LNT_AutoConfigPlugin','PluginBase','implements','Vanilla plugin example owns JSON settings'),('LNT_AutoConfigPlugin','JsonFileLoader','calls','Loads settings and saves first-run defaults'),('LNT_ServerModule','LNT_ModuleBase','implements','Server specialization of lifecycle contract'),('LNT_ClientModule','LNT_ModuleBase','implements','Client specialization of lifecycle contract'),('LNT_ModuleManager','LNT_ServerModule','references','OnServerUpdate dispatches by typed cast'),('LNT_ModuleManager','LNT_ClientModule','references','OnClientUpdate dispatches by typed cast'),('LNT_ModuleBase','LNT_RPC','conceptually_related_to','Modules register handlers early during OnInit'),('Community Framework','LNT_ModuleManager','conceptually_related_to','Contrasts opt-in framework modules with explicit custom manager')]),
('ScriptRPC|ParamsReadContext|PlayerIdentity|DayZGame|LNT_RPC|LNT_RpcHandler|LNT_Permissions|OnClientReadyEvent|ERPCs|Community Framework|Read/Write Contract',[
('ScriptRPC','ParamsReadContext','shares_data_with','Read and write types and field order must match'),('ScriptRPC','PlayerIdentity','references','Recipient selects unicast; null destination depends on sending side'),('DayZGame','LNT_RPC','calls','Single owned engine ID dispatches router'),('LNT_RPC','LNT_RpcHandler','calls','Named registry dispatches OnReceive'),('LNT_RPC','ScriptRPC','calls','CreateRPC writes mod and function headers'),('LNT_Permissions','PlayerIdentity','references','Server validates sender GetPlainId before privileged action'),('OnClientReadyEvent','ScriptRPC','calls','Pushes display configuration to ready client'),('ERPCs','LNT_RPC','conceptually_related_to','Custom engine IDs avoid vanilla enum range'),('Community Framework','LNT_RPC','conceptually_related_to','Named routing comparison contrasts framework and standalone approaches'),('Read/Write Contract','ParamsReadContext','rationale_for','Reject failed reads to prevent misaligned payload parsing')]),
('JsonFileLoader|FileHandle|FPrintln|CloseFile|$profile|MakeDirectory|LNT_ConfigBase|LNT_ConfigField|ConfigVersion|Auto-Save Timers|Dirty Flag|OnMissionFinish',[
('JsonFileLoader','$profile','references','Config examples persist under mod-specific profile paths'),('FPrintln','FileHandle','references','Writes manual JSON or log lines to open handle'),('CloseFile','FileHandle','references','Closes acquired handle after I/O'),('MakeDirectory','$profile','references','Creates each missing parent directory individually'),('LNT_ConfigBase','LNT_ConfigField','references','GetFields returns descriptors for generic config UI'),('ConfigVersion','JsonFileLoader','references','Loaded version controls sequential migration and resave'),('Auto-Save Timers','Dirty Flag','references','Only saves changed data on timed intervals'),('OnMissionFinish','Dirty Flag','references','Flushes unsaved state on shutdown')]),
('LNT_Permissions|LNT_PermissionsData|PlayerIdentity|LNT_UserGroup|LNT_GroupManager|LNT_PermNode|LNT_PermState|JsonFileLoader|Default deny|Prefix Wildcard|Superadmin',[
('LNT_Permissions','LNT_PermissionsData','references','Stores Steam64 IDs mapped to capability arrays'),('LNT_Permissions','PlayerIdentity','references','Authenticated GetPlainId keys permission lookup'),('LNT_GroupManager','LNT_UserGroup','references','Resolves member permissions from named groups'),('LNT_PermNode','LNT_PermState','references','Nodes carry ALLOW DENY or INHERIT state'),('LNT_Permissions','Prefix Wildcard','references','Grants matching dot-separated capability subtree'),('LNT_Permissions','Superadmin','references','Full wildcard grants all capabilities in shared store'),('LNT_Permissions','JsonFileLoader','calls','Migrates legacy admin list to hierarchical JSON data'),('Default deny','LNT_Permissions','rationale_for','Missing permission or invalid identity rejects privileged action')]),
('ScriptInvoker|LNT_EventBus|LNT_EventArgs|LNT_PlayerEventArgs|LNT_TypedEventManager|Managed|Param|OnMissionFinish|LanternCore|EScriptInvokerRemoveFlags',[
('LNT_EventBus','ScriptInvoker','references','Named and custom channels dispatch subscribers'),('LNT_PlayerEventArgs','LNT_EventArgs','implements','Concrete typed player event payload'),('LNT_TypedEventManager','ScriptInvoker','references','Maps args runtime type name to invoker channel'),('LNT_TypedEventManager','LNT_EventArgs','references','Raise routes one typed payload object'),('LNT_EventBus','Param','references','Custom event channel carries wrapped payload'),('ScriptInvoker','EScriptInvokerRemoveFlags','references','Default ALL removal clears duplicate registrations'),('ScriptInvoker','Managed','conceptually_related_to','Managed weak callback references null on destruction'),('OnMissionFinish','LNT_EventBus','references','Modules remove event subscriptions during teardown'),('LanternCore','LNT_EventBus','calls','ShutdownAll clears invokers as final safety net')]),
('Batched Processing|Widget Pooling|Search Debouncing|Update Rate Limiting|Caching|VehicleRegistry|CarScript|GetObjectsAtPosition3D|LNT_TrackedVehicle|Dirty Flag|GetTickTime',[
('VehicleRegistry','CarScript','references','EEInit registers; EEDelete unregisters entities'),('VehicleRegistry','GetObjectsAtPosition3D','conceptually_related_to','Registry replaces repeated map-wide scans'),('LNT_TrackedVehicle','VehicleRegistry','conceptually_related_to','Intrusive linked-list variant avoids array removal scans'),('Widget Pooling','Search Debouncing','conceptually_related_to','Together avoid rebuilding long lists on every keystroke'),('Update Rate Limiting','Batched Processing','conceptually_related_to','Distributes expensive work over frame budgets'),('Caching','GetObjectsAtPosition3D','conceptually_related_to','Avoids repeating expensive world queries'),('Dirty Flag','Caching','conceptually_related_to','Recompute sorted UI only after mutation'),('GetTickTime','Batched Processing','references','Measure elapsed time before and after optimization')]),
('DayZ Tools|Workdrive|mod.cpp|config.cpp|CfgPatches|CfgMods|5_Mission|MissionServer|MissionGameplay|Addon Builder|PBO|File Patching',[
('DayZ Tools','Addon Builder','references','Tool suite includes PBO packer'),('Workdrive','DayZ Tools','references','Mounts shared P development drive'),('config.cpp','CfgPatches','references','Declares addon identity and dependencies'),('config.cpp','CfgMods','references','Defines script compilation paths'),('CfgMods','5_Mission','references','Registers missionScriptModule'),('5_Mission','MissionServer','references','Server hello-world initialization override'),('5_Mission','MissionGameplay','references','Client hello-world initialization override'),('Addon Builder','PBO','references','Packs Scripts folder with virtual prefix'),('File Patching','PBO','conceptually_related_to','Accelerates script iteration; config and added files still require rebuild')]),
('MFM_FieldJournal|Inventory_Base|CfgVehicles|Hidden Selections|P3D|PAA|TexView2|types.xml|stringtable.csv|Data PBO|Scripts PBO|CfgSoundSets',[
('MFM_FieldJournal','Inventory_Base','implements','Item config and script inherit inventory base'),('CfgVehicles','MFM_FieldJournal','references','Defines item scope model dimensions and damage'),('MFM_FieldJournal','Hidden Selections','references','Overrides camoGround texture'),('Hidden Selections','P3D','references','Selection names must exist in model'),('TexView2','PAA','references','Converts source images to engine textures'),('types.xml','MFM_FieldJournal','references','Registers Central Economy spawn population and locations'),('MFM_FieldJournal','stringtable.csv','references','Localized displayName and description resolve STR keys'),('Data PBO','Scripts PBO','conceptually_related_to','Separate asset definitions from behavior for independent rebuilds'),('MFM_FieldJournal','CfgSoundSets','references','Optional journal-open sound uses shader and soundset definitions')]),
('AdminDemoPanel|AdminDemoConfig|AdminDemoRPC|ScriptedWidgetEventHandler|RPCSingleParam|PlayerBase|PlayerIdentity|DayZGame|MissionGameplay|ParamsReadContext|CreateWidgets|FindAnyWidget',[
('AdminDemoPanel','ScriptedWidgetEventHandler','implements','Receives button click callbacks'),('AdminDemoPanel','CreateWidgets','calls','Open loads the panel layout'),('AdminDemoPanel','FindAnyWidget','calls','Binds and caches named controls'),('AdminDemoPanel','RPCSingleParam','calls','Refresh requests server player information'),('PlayerBase','AdminDemoConfig','calls','Server request handler verifies admin whitelist'),('AdminDemoConfig','PlayerIdentity','references','Matches GetPlainId to allowed Steam64 IDs'),('RPCSingleParam','AdminDemoRPC','references','Uses request and response identifiers'),('PlayerBase','RPCSingleParam','calls','Responds only to requestor with target null'),('DayZGame','ParamsReadContext','calls','Deserializes matching Param2 int and string response'),('DayZGame','AdminDemoPanel','calls','Routes returned player information to open panel'),('MissionGameplay','AdminDemoPanel','references','Owns panel initialization keyboard toggle and teardown')]),
('ChatInputMenu|CCmdRPC|CCmdBase|CCmdRegistry|CCmdHeal|PlayerBase|PlayerIdentity|DayZGame|RPCSingleParam|MissionServer|EditBoxWidget|LNT_Permissions',[
('ChatInputMenu','EditBoxWidget','references','Reads submitted widget argument instead of private vanilla field'),('ChatInputMenu','RPCSingleParam','calls','Intercepts slash commands before normal chat broadcast'),('CCmdRegistry','CCmdBase','references','Maps normalized command names to handler instances'),('CCmdHeal','CCmdBase','implements','Concrete server heal command'),('CCmdHeal','PlayerBase','calls','Restores health blood shock energy water and clears bleeding'),('PlayerBase','CCmdRegistry','calls','Parses command and resolves handler'),('PlayerBase','PlayerIdentity','references','Server admin check uses authenticated sender GetPlainId'),('MissionServer','CCmdRegistry','calls','Registers commands during OnInit'),('CCmdBase','RPCSingleParam','calls','Sends target-less feedback to caller only'),('DayZGame','CCmdRPC','references','Receives feedback ID and displays local chat'),('LNT_Permissions','CCmdBase','conceptually_related_to','Production permissions replace tutorial hardcoded allow-list')])
]
for f,(labels,relations) in zip(files,specs):
    title=next(x[2:].strip() for x in texts[f].splitlines() if x.startswith('# '))
    doc='doc_'+re.sub('[^a-z0-9]+','_',f.lower()).strip('_')
    nodes[doc]=dict(id=doc,label=title,file_type='document',source_file=f,source_location='line 1',source_url=None,captured_at=None,author=None,contributor=None)
    for label in labels.split('|'):edge(doc,node(label,f),f)
    for a,b,r,why in relations:
        if (a,b) in [('RestApi','JsonFileLoader'),('LanternCore','LNT_BanManager')]:continue
        ak=node(a,f);bk=node(b,f)
        edge(ak,bk,f,r,why)
        edges[-1]['source_location']=loc(f,a)
        if edges[-1]['source_location']=='line 1':edges[-1]['source_location']=loc(f,b)
    for match in re.finditer(r'\[[^\]]+\]\(([^)#]+\.md)(?:#[^)]*)?\)',texts[f]):
        target=(Path(f).parent/match.group(1)).resolve()
        try:rel=target.relative_to(Path.cwd()).as_posix()
        except ValueError:continue
        if rel not in files or rel==f:continue
        td='doc_'+re.sub('[^a-z0-9]+','_',rel.lower()).strip('_')
        edge(doc,td,f,'references','Explicit internal chapter link')
        edges[-1]['source_location']='line '+str(texts[f][:match.start()].count('\n')+1)

# Cross-cutting similarities are interpretive and individually scored.
for a,b,i,score,why in [
('ParticleManager','Widget Pooling',5,.88,'Both amortize creation cost through reusable pools, across rendering effects and UI'),
('PluginRecipesManager','CCmdRegistry',20,.84,'Both discover named operations through registries before validating and executing them'),
('ConstructionPart','LNT_PermNode',14,.66,'Both encode parent/dependency structure, but construction requirements differ from permission inheritance')]:
    edge(cid(a),cid(b),files[i],'semantically_similar_to',why,'INFERRED',score)

for label,i,why in [
('SEffectManager',0,'One-shot effects require autodestroy and entity loops require explicit stop, preventing retained registry entries.'),
('ParticleManager',5,'Pool owns ParticleSource lifetime; render effects on clients and clean high-level SEffectManager registrations.'),
('LNT_ModuleManager',11,'Typed server and client modules avoid double update dispatch on listen servers; centralized cleanup bounds mission state.'),
('LNT_RPC',12,'Namespace plus function name separates routes within the router; handlers register early and validate authority server-side.'),
('ScriptInvoker',15,'Pair Insert with Remove and document callback signatures; teardown order requires null checks.'),
('Widget Pooling',16,'Reuse rows and debounce searches to avoid repeated widget allocation during UI refresh.'),
('ChatInputMenu',20,'Intercept completed slash-command input before vanilla ChatPlayer broadcast; route authoritative execution to server.')]:node(label,files[i],why)

# Preserve explicitly conflicting documentation as review questions, not asserted APIs.
for label,i,why,a,b in [
('Config initialization guidance conflict',11,'Module lifecycle rules forbid config loading in OnInit, while the same chapter self-loading plugin example performs it there. Startup policy needs reconciliation.','LNT_AutoConfigPlugin','LNT_ModuleBase'),
('Crafting registration guidance conflict',18,'Custom item tutorial suggests CfgRecipes config registration; the dedicated crafting chapter specifies RecipeBase subclasses and RegisterRecipies. Treat this tutorial suggestion as unresolved.','CfgRecipes','RecipeBase')]:
    ak=node(a,files[i],why);bk=node(b,files[i]);edge(ak,bk,files[i],'conceptually_related_to',why,'AMBIGUOUS',.2)
    edges[-1]['source_location']=loc(files[i],a)

hyperedges=[]
for n,label,ls,i in [
('sound_pipeline','Configured sound to live wave','CfgSoundShaders|CfgSoundSets|SoundParams|SoundObjectBuilder|SoundObject|AbstractSoundScene|AbstractWave',0),
('crafting_pipeline','Recipe discovery validation and timed execution','CraftingManager|PluginRecipesManager|RecipeBase|ActionWorldCraft|CAContinuousCraft',1),
('admin_roundtrip','Admin player-info request authorization response and UI update','AdminDemoPanel|AdminDemoConfig|AdminDemoRPC|PlayerBase|DayZGame|RPCSingleParam',19)]:
    hyperedges.append(dict(id='chunk04_'+n,label=label,nodes=[cid(s) for s in ls.split('|')],relation='participate_in',confidence='EXTRACTED',confidence_score=1.0,source_file=files[i]))

assert len(specs)==len(files)==21
assert all(e['source'] in nodes and e['target'] in nodes for e in edges)
assert all(x in nodes for h in hyperedges for x in h['nodes'])
dedup={}
for e in edges:dedup.setdefault((e['source'],e['target'],e['relation'],e['source_file'],e['confidence']),e)
out=dict(nodes=list(nodes.values()),edges=list(dedup.values()),hyperedges=hyperedges,input_tokens=0,output_tokens=0)
Path('graphify-out/.graphify_chunk_04.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps({'nodes':len(nodes),'edges':len(dedup),'hyperedges':len(hyperedges),'documents':21}))
