import json,re
from pathlib import Path
root=Path.cwd()
files=[Path(x) for x in json.loads(Path('graphify-out/.files_02.json').read_text())]
nodes={}; edges=[]
def cid(s): return 'dayz_'+re.sub(r'[^a-z0-9]+','_',s.lower()).strip('_')
def node(label,f,heading,kind='rationale',rationale=None):
    k=cid(label)
    if k not in nodes:
        nodes[k]=dict(id=k,label=label,file_type=kind,source_file=f,source_location=heading,source_url=None,captured_at=None,author=None,contributor=None)
    if rationale: nodes[k]['rationale']=rationale
    return k
def edge(a,b,f,h,relation='references',confidence='EXTRACTED',score=1.0,detail=None):
    d=dict(source=a,target=b,relation=relation,confidence=confidence,confidence_score=score,source_file=f,source_location=h,weight=1.0)
    if detail:d['description']=detail
    edges.append(d)
specs=[
('mod.cpp & Workshop','mod.cpp|Steam Workshop|DayZ Launcher|meta.cpp|stringtable.csv|Split Mod Pattern|config.cpp|Server Mod','Overview',[
('DayZ Launcher','mod.cpp','references','Reads visual metadata'),('DayZ Launcher','meta.cpp','references','Links local files with Workshop item'),('meta.cpp','Steam Workshop','references','Stores publishedid'),('mod.cpp','stringtable.csv','references','Supports localized $STR_ text')]),
('Anatomy of a Minimal Mod','CfgPatches|CfgMods|MissionServer|MissionGameplay|5_Mission|modded class|Print|File Patching|PBO','The Three-File Skeleton',[
('CfgMods','5_Mission','references','Registers missionScriptModule files'),('MissionServer','Print','calls','HelloMod OnInit sample writes server log'),('MissionGameplay','Print','calls','HelloMod OnInit sample writes client log'),('modded class','MissionServer','references','Extends mission lifecycle while preserving super calls')]),
('File Organization Best Practices','3_Game|4_World|5_Mission|Scripts PBO|Data PBO|GUI PBO|stringtable.csv|requiredAddons|Class Prefixes','The Canonical Directory Structure',[
('Scripts PBO','3_Game','references','Shared configs RPCs and data classes'),('Scripts PBO','4_World','references','Entity behaviors and world managers'),('Scripts PBO','5_Mission','references','Mission hooks and UI'),('GUI PBO','Layout Files','references','Contains layouts imagesets and styles'),('Data PBO','P3D','references','Contains physical assets')]),
('Server vs Client Architecture','Dedicated Server|Client|Listen Server|RPC|SERVER Define|IsServer|IsClient|MissionServer|MissionGameplay|Server Authority|requiredAddons','The Three Execution Contexts',[
('Dedicated Server','MissionServer','references','Server mission lifecycle'),('Client','MissionGameplay','references','Client presentation lifecycle'),('Listen Server','IsServer','references','Returns true'),('Listen Server','IsClient','references','Returns true'),('RPC','Server Authority','references','Client requests must be validated on server'),('SERVER Define','Dedicated Server','references','Compile-time dedicated binary distinction')]),
('Widget Types','Widget|WorkspaceWidget|TextWidget|ImageWidget|ButtonWidget|SliderWidget|EditBoxWidget|FindAnyWidget|Widget Pooling','How Widgets Work',[
('WorkspaceWidget','Widget','implements','Widget base class'),('TextWidget','Widget','implements','Widget base class'),('ImageWidget','Widget','implements','Widget base class'),('ButtonWidget','Widget','implements','Widget base class'),('FindAnyWidget','Layout Files','references','String names must match declared widgets')]),
('Layout File Format (.layout)','Layout Files|Widget|scriptclass|ScriptParamsClass|OnWidgetScriptInit|ScriptedWidgetEventHandler|SetHandler|fixaspect|Dabs Framework','Script Integration',[
('Layout Files','Widget','references','Defines one rooted widget tree'),('scriptclass','OnWidgetScriptInit','references','Engine invokes named initializer after tree creation'),('ScriptParamsClass','scriptclass','references','Fills reference scalar fields before initialization'),('OnWidgetScriptInit','SetHandler','calls','Handler examples explicitly attach themselves'),('Dabs Framework','ScriptParamsClass','references','Uses declarative data binding mechanism')]),
('Sizing & Positioning','Proportional Sizing|Pixel Sizing|Exact Flags|Alignment References|fixaspect|UI Scaling|Widget Priority|SetScreenPos','The Core Concept: Proportional vs. Pixel',[
('Exact Flags','Proportional Sizing','references','Zero selects parent-relative axis'),('Exact Flags','Pixel Sizing','references','One selects exact pixel axis'),('fixaspect','ImageWidget','references','Preserves image aspect ratio'),('Widget Priority','Widget','references','Rendering order applies among siblings')]),
('Container Widgets','FrameWidgetClass|WrapSpacerWidget|GridSpacerWidget|ScrollWidget|Scrollable Dynamic Lists|Size To Content|Widget Pooling|Update','The ScrollWidget + WrapSpacer Pattern',[
('Scrollable Dynamic Lists','ScrollWidget','references','Fixed height viewport'),('Scrollable Dynamic Lists','WrapSpacerWidget','references','Growing child content'),('WrapSpacerWidget','Update','calls','Examples explicitly recalculate after adding/removing children'),('WrapSpacerWidget','Size To Content','references','Adapts size to children'),('GridSpacerWidget','Widget','implements','Uniform grid container')]),
('Programmatic Widget Creation','CreateWidgets|CreateWidget|WorkspaceWidget|WidgetFlags|ARGB|SetUserData|Unlink|Widget Pooling|FindAnyWidget','Two Approaches',[
('WorkspaceWidget','CreateWidgets','references','Loads layout trees'),('WorkspaceWidget','CreateWidget','references','Creates individual widgets'),('CreateWidgets','Layout Files','references','Instantiates root and descendants'),('CreateWidget','WidgetFlags','references','Flags configure coordinate modes and input'),('Widget Pooling','CreateWidgets','calls','WidgetPool constructor and Acquire allocate only when needed'),('Unlink','Widget','references','Destroys widget and descendants; clear dangling script refs')]),
('Event Handling','ScriptedWidgetEventHandler|SetHandler|OnClick|OnChange|WidgetEventHandler|Event Propagation|CallLater|OnDrag|OnDrop','ScriptedWidgetEventHandler',[
('SetHandler','ScriptedWidgetEventHandler','references','Attaches one handler instance'),('ScriptedWidgetEventHandler','OnClick','references','Virtual callback override'),('ScriptedWidgetEventHandler','OnChange','references','Receives changed values'),('OnClick','Event Propagation','references','True consumes false bubbles to parent'),('WidgetEventHandler','OnClick','references','Named callback registration'),('OnClick','CallLater','calls','Heavy action example defers work to GUI queue')]),
('Styles, Fonts & Images','Widget Styles|SDF Fonts|Imagesets|ImageWidget|CfgMods|Color Theme|ARGB|TexView2','Creating Custom Imagesets',[
('Imagesets','ImageWidget','references','Named atlas regions supply image slots'),('CfgMods','Imagesets','references','defs imageSets files register atlases'),('Imagesets','TexView2','references','Source atlas converted for engine use'),('Color Theme','ARGB','references','Centralizes color constants'),('SDF Fonts','UI Scaling','conceptually_related_to','Maintains crisp text across scales')]),
('Dialogs & Modals','UIScriptedMenu|UIManager|ShowDialog|OnModalResult|ScriptedWidgetEventHandler|UIScriptedWindow|ChangeGameFocus|SetSort|CallLater','The four dialog systems',[
('UIScriptedMenu','UIManager','references','Menu stack owns lifecycle'),('UIScriptedMenu','ChangeGameFocus','calls','OnShow and OnHide use LockControls and UnlockControls'),('ShowDialog','OnModalResult','references','Result callback carries code and button'),('UIScriptedWindow','UIManager','references','OpenWindow and CloseWindow manage windows'),('ScriptedWidgetEventHandler','ChangeGameFocus','references','Manual dialogs balance focus increments'),('UIScriptedWindow','MissionGameplay','references','CreateScriptedWindow hook creates custom window')]),
('Production UI Architecture Patterns','LNT_PanelModule|LNT_Form|LNT_Window|LNT_ViewModel|LNT_Palette|LNT_Scheme|LNT_Branding|LNT_Command|LNT_CommandManager|Widget Pooling|NotificationSystem','Module-Form-Window Admin Panels',[
('LNT_PanelModule','LNT_Window','references','Owns window'),('LNT_PanelModule','LNT_Form','references','Creates form'),('LNT_Window','LNT_Form','calls','Load invokes form.Attach'),('LNT_ViewModel','FindAnyWidget','calls','NotifyPropertyChanged resolves named property widget'),('LNT_Scheme','LNT_Palette','calls','Semantic roles obtain palette colors'),('LNT_Branding','ImageWidget','references','Applies logo'),('LNT_CommandManager','LNT_Command','calls','Run checks CanExecute and Execute; UndoLast calls Undo')]),
('Advanced Widgets','RichTextWidget|HtmlWidget|CanvasWidget|MapWidget|ItemPreviewWidget|PlayerPreviewWidget|VideoWidget|RenderTargetWidget|RTTextureWidget|EntityAI|GetScreenPosRelative','Summary',[
('RichTextWidget','TextWidget','implements','Extends TextWidget'),('HtmlWidget','RichTextWidget','implements','Extends rich text with LoadFile'),('ItemPreviewWidget','EntityAI','references','SetItem needs spawned entity reference'),('CanvasWidget','GetScreenPosRelative','references','World overlay examples project world points to pixel coordinates'),('MapWidget','CanvasWidget','references','Vanilla map scale ruler uses canvas overlay'),('ImageWidget','RTTextureWidget','references','SetImageTexture uses render texture as source')]),
('Textures (.paa, .edds, .tga)','PAA|EDDS|TGA|PNG|TexView2|DXT1|DXT5|Mipmaps|Normal Maps|hiddenSelectionsTextures','Texture Formats Overview',[
('TexView2','PAA','references','Converts source textures to runtime format'),('EDDS','PAA','references','Binarization conversion described'),('PAA','Mipmaps','references','Contains mip chain'),('PAA','DXT1','references','Opaque compression'),('PAA','DXT5','references','Smooth alpha compression'),('hiddenSelectionsTextures','PAA','references','Texture variants avoid model duplication')]),
('3D Models (.p3d)','P3D|MLOD|ODOL|Object Builder|Geometry LOD|Memory Points|Named Selections|Proxies|model.cfg|Binarize','P3D Format Overview',[
('P3D','MLOD','references','Editable source form'),('P3D','ODOL','references','Optimized binary form'),('Binarize','MLOD','references','Consumes editable model'),('Binarize','ODOL','references','Produces optimized model'),('P3D','Geometry LOD','references','Convex collision components with mass'),('P3D','Memory Points','references','Named positions in memory LOD'),('model.cfg','Named Selections','references','Animation targets'),('Proxies','P3D','references','Attachment model references')]),
('Materials (.rvmat)','RVMAT|P3D|Super Shader|Glass Shader|Texture Stages|Normal Maps|hiddenSelectionsMaterials|healthLevels|uvTransform|specularPower','Texture Stages',[
('P3D','RVMAT','references','Faces assigned material'),('RVMAT','Super Shader','references','PixelShaderID and VertexShaderID bind shader'),('RVMAT','Texture Stages','references','Stage classes map shader inputs'),('Texture Stages','Normal Maps','references','Super Stage1 normal map'),('healthLevels','RVMAT','references','Damage thresholds select material'),('hiddenSelectionsMaterials','RVMAT','references','Overrides per-selection material'),('uvTransform','Texture Stages','references','Controls UV scale offset and tiling')]),
('Audio (.ogg, .wss)','OGG Vorbis|WSS|CfgSoundShaders|CfgSoundSets|CfgSoundCurves|Spatial Audio|SEffectManager|EffectSound|config.cpp','CfgSoundShaders and CfgSoundSets',[
('config.cpp','CfgSoundShaders','references','Declares raw sample configuration'),('config.cpp','CfgSoundSets','references','Declares playback behavior'),('CfgSoundSets','CfgSoundShaders','references','soundShaders array combines samples'),('CfgSoundShaders','OGG Vorbis','references','samples paths resolve audio'),('CfgSoundSets','CfgSoundCurves','references','volumeCurve names attenuation class'),('Spatial Audio','OGG Vorbis','references','Mono samples required by documented pipeline'),('SEffectManager','CfgSoundSets','references','PlaySound references SoundSet names'),('SEffectManager','EffectSound','references','Playback creates effect handle')]),
('DayZ Tools Workflow','DayZ Tools|Workdrive|Object Builder|TexView2|ImageToPAA|Terrain Builder|Binarize|AddonBuilder|Workbench|Publisher','DayZ Tools Suite Overview',[
('DayZ Tools','Object Builder','references','Includes model editor'),('DayZ Tools','Workbench','references','Includes scripting IDE'),('DayZ Tools','AddonBuilder','references','Includes packer'),('DayZ Tools','Terrain Builder','references','Includes terrain authoring'),('ImageToPAA','PAA','references','Command-line conversion'),('Object Builder','Workdrive','references','Uses shared P drive asset root'),('Publisher','Steam Workshop','references','Uploads finished mods')]),
('PBO Packing','PBO|PBO Prefix|AddonBuilder|Binarize|packonly|Key Signing|bikey|bisign|requiredAddons|Multi-PBO Builds','PBO Internal Structure',[
('PBO','PBO Prefix','references','Maps virtual filesystem path'),('AddonBuilder','Binarize','calls','Optional preprocessing stage'),('AddonBuilder','PBO','references','Packs archive'),('packonly','Binarize','references','Skips binarization'),('Key Signing','bikey','references','Public verification key'),('Key Signing','bisign','references','Archive signature'),('Multi-PBO Builds','requiredAddons','references','CfgPatches orders dependent packages')]),
('Workbench Guide','Workbench|DayZDiag|gproj|Workdrive|ScriptModules|File Patching|Script Profiler|EnProfiler|Layout Files|Imagesets','Project Files (.gproj)',[
('Workbench','gproj','references','Loads project filesystem modules and styles'),('gproj','ScriptModules','references','Maps engine layers to paths'),('gproj','Imagesets','references','Supplies resources for layout previews'),('Workbench','DayZDiag','references','Attaches debugger'),('Workbench','Layout Files','references','Previews hierarchy without runtime behavior'),('File Patching','DayZDiag','references','Diagnostic executable loads loose development files'),('Script Profiler','EnProfiler','references','Programmatic profiler API')]),
]
for p,(title,concepts,h,rels) in zip(files,specs):
    f=p.relative_to(root).as_posix(); did='doc_'+re.sub(r'[^a-z0-9]+','_',f.lower()).strip('_')
    nodes[did]=dict(id=did,label=title,file_type='document',source_file=f,source_location='# '+title,source_url=None,captured_at=None,author=None,contributor=None)
    for c in concepts.split('|'):edge(did,node(c,f,h),f,h)
    for a,b,r,d in rels:
        edge(node(a,f,h),node(b,f,h),f,h,r,detail=d)
f=files[16].relative_to(root).as_posix()
edge(cid('Super Shader'),cid('Texture Stages'),f,'File Structure; Stage Assignments for the Super Shader; Creating an RVMAT from Scratch','references','AMBIGUOUS',.2,'Reference table specifies Stage2 detail, Stage3 macro and Stage5 specular, but worked code uses diffuse at Stage2 and specular at Stage3; needs source review.')
f=files[3].relative_to(root).as_posix()
edge(cid('mod.cpp'),cid('Server Mod'),f,'The mod.cpp type Field','references','AMBIGUOUS',.2,'This chapter attributes execution scope to metadata type; mod.cpp chapter Theory vs Practice says launch flags actually control loading.')
node('Widget Pooling',f,'',rationale='Reuse list widgets to avoid repeated allocation and layout recalculation during frequent updates.')
node('Server Authority',f,'The Golden Rules',rationale='Validate client requests server-side so clients cannot authorize game-state changes.')
node('Class Prefixes',files[2].relative_to(root).as_posix(),'Naming Conventions',rationale='Script class names are globally shared even when files are organized in separate mod directories.')
node('Multi-PBO Builds',files[19].relative_to(root).as_posix(),'Multi-PBO Mod Builds',rationale='Separate fast script rebuilds from expensive asset binarization and split archives before size limits.')
edge(cid('PBO Prefix'),cid('FindAnyWidget'),files[19].relative_to(root).as_posix(),'The -prefix Flag','semantically_similar_to','INFERRED',.75,'Both form string-based resource contracts that fail when definitions and runtime references disagree, across packaging and GUI domains.')
hyper=[]
for ident,label,ls,i,h in [
('module_form_window','Module Form Window UI composition',['LNT_PanelModule','LNT_Form','LNT_Window'],12,'Module-Form-Window Admin Panels'),
('theme_layers','Palette scheme and branding',['LNT_Palette','LNT_Scheme','LNT_Branding'],12,'A Three-Layer Theme System'),
('asset_pipeline','Source to packed game asset pipeline',['Object Builder','TexView2','Binarize','AddonBuilder','PBO'],18,'Complete Workflow: Source to Game')]:
    hyper.append(dict(id=ident,label=label,nodes=[cid(x) for x in ls],relation='participate_in',confidence='EXTRACTED',confidence_score=1.,source_file=files[i].relative_to(root).as_posix(),source_location=h))
out=dict(nodes=list(nodes.values()),edges=edges,hyperedges=hyper,input_tokens=0,output_tokens=0)
Path('graphify-out/.graphify_chunk_02.json').write_text(json.dumps(out,indent=2),encoding='utf-8')
print(len(nodes),len(edges),len(hyper))
